make .close() method idempotent
omnilib/aiosqlite pull request #238
Opened 2023-05-02 15:38 UTC by zzzeek

While not explicitly documented in pep-249, repeated calls to connection.close() are customarily accepted without error; the sqlite3 module itself allows multiple calls to .close() as do popular asyncio database drivers such as asyncpg.

Prior to this change, the .close() method would attempt to execute a command within the thread, however since the _connection attribute is None, it would raise ValueError("no active connection"). This ValueError is also not pep-249 compliant since all exceptions raised should be subclasses of dbapi.Error, so if the aiosqlite project would prefer repeated .close() calls raise, it should raise within the dbapi.Error hierarchy.

The change here is submitted by the maintainers of SQLAlchemy (https://www.sqlalchemy.org) for the benefit of projects to reduce warnings emitted during various connection, application, and interpreter shutdown scenarios.

following the [Contributor guide](https://github.com/omnilib/aiosqlite/blob/main/CONTRIBUTING.md) I did not see specifics on how to add changelog entries and no issue number was required.

2023-05-06 19:39 UTC, amyreese requested changes
Needs formatting fix since I can't push a commit to your branch. You can use `make format` from a venv, as mentioned in the contributor guide, or format with the apporpriate version of black.

2023-05-07 12:39 UTC, zzzeek commented
seems I missed the "make format".

that's pushed now

2023-05-07 17:15 UTC, amyreese approved these changes

2023-05-07 17:15 UTC, merged

2023-05-07 17:16 UTC, amyreese commented
Thank you!

2023-06-23 17:15 UTC, abompard commented
Hey folks! I've been hit by this because a `rollback()` was automatically issued on the second `close()`, and the `rollback()` operation is not protected as the `close()` is by this PR. Do you think it would make sense to add the same protection to `rollback()`?