Throw when connection is closed and we try to execute commands
omnilib/aiosqlite pull request #79
Opened 2020-08-19 13:07 UTC by mariano54

### Description

I ran into an issue where I had an asyncio method calling fetchall() on a Cursor, but it hung forever. This is because the connection was closed, and the loop stopped running so the fetchall future was never pulled out of the queue.

This PR changes _execute so it checks for whether the connection is open or not. _connect also has to be changed, because it used to call _execute (which would throw if there is no connection yet). Is this the right approach? If there is a better way to do it, I can implement it.

2020-09-10 15:58 UTC, hoffmang9 commented
Is there anything we can further do to get this merged?

2020-09-12 20:50 UTC, jreese requested changes
Functionality looks good, but I'd like to see better test cases verifying that functionality.

2020-09-12 20:50 UTC, jreese commented on aiosqlite/tests/smoke.py
> +            await cursor.fetchall()
Would prefer to see something like `with self.assertRaisesRegex(ValueError, "connection closed")` to also ensure this catches the specific exception it's expecting to catch.

2020-09-12 20:50 UTC, jreese commented on aiosqlite/tests/smoke.py
> +                pass
Is there a way to make sure the tasks are returning (or throwing) the expected values/exceptions?

2021-01-19 07:53 UTC, mariano54 commented
Would you mind taking another look and merging? it would help us out to have this included in a release.

Thanks :)

2021-02-07 06:25 UTC, hoffmang9 commented
Checking in on this. Is there anything further you need from @mariano54 ?

2021-02-22 00:18 UTC, merged

2021-02-22 00:18 UTC, jreese commented
Sorry for the delay on returning to this. Thank you for the fixes!

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/tests/smoke.py
> +    async def test_cursor_on_closed_connection(self):
async def test_cursor_on_closed_connection(self):

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/tests/smoke.py
> +        db = await aiosqlite.connect(TEST_DB)
db = await aiosqlite.connect(TEST_DB)

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/tests/smoke.py
> +        cursor = await db.execute("select 1, 2")
cursor = await db.execute("select 1, 2")

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/tests/smoke.py
> +        await db.close()
await db.close()

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/tests/smoke.py
> +        with self.assertRaisesRegex(ValueError, "Connection closed"):
with self.assertRaisesRegex(ValueError, "Connection closed"):

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/tests/smoke.py
> +            await cursor.fetchall()
await cursor.fetchall()

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/tests/smoke.py
> +        with self.assertRaisesRegex(ValueError, "Connection closed"):
with self.assertRaisesRegex(ValueError, "Connection closed"):

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/tests/smoke.py
> +            await cursor.fetchall()
await cursor.fetchall()

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/tests/smoke.py
> +    async def test_cursor_on_closed_connection_loop(self):
async def test_cursor_on_closed_connection_loop(self):

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/tests/smoke.py
> +        db = await aiosqlite.connect(TEST_DB)
db = await aiosqlite.connect(TEST_DB)

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/tests/smoke.py
> +        cursor = await db.execute("select 1, 2")
cursor = await db.execute("select 1, 2")

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/tests/smoke.py
> +        tasks = []
tasks = []

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/tests/smoke.py
> +        for i in range(100):
for i in range(100):

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/tests/smoke.py
> +            if i == 50:
if i == 50:

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/tests/smoke.py
> +                tasks.append(asyncio.ensure_future(db.close()))
tasks.append(asyncio.ensure_future(db.close()))

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/tests/smoke.py
> +            tasks.append(asyncio.ensure_future(cursor.fetchall()))
tasks.append(asyncio.ensure_future(cursor.fetchall()))

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/tests/smoke.py
> +        for task in tasks:
for task in tasks:

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/tests/smoke.py
> +            try:
try:

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/tests/smoke.py
> +                await task
await task

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/tests/smoke.py
> +            except sqlite3.ProgrammingError:
except sqlite3.ProgrammingError:

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/tests/smoke.py
> +                pass
pass

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/core.py
> -        while self._running:
while self._running:

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/core.py
> +        while True:
while True:

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/core.py
> +            # Continues running until all queue items are processed,
# Continues running until all queue items are processed,

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/core.py
> +            # even after connection is closed (so we can finalize all
# even after connection is closed (so we can finalize all

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/core.py
> +            # futures)
# futures)

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/core.py
> +                if self._running:
if self._running:

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/core.py
> +                    continue
continue

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/core.py
> +                break
break

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/core.py
> +        if not self._running or not self._connection:
if not self._running or not self._connection:

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/core.py
> +            raise ValueError("Connection closed")
raise ValueError("Connection closed")

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/core.py
> -                self._connection = await self._execute(self._connector)
self._connection = await self._execute(self._connector)

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/core.py
> +                future = asyncio.get_event_loop().create_future()
future = asyncio.get_event_loop().create_future()

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/core.py
> +                self._tx.put_nowait((future, self._connector))
self._tx.put_nowait((future, self._connector))

2024-09-29 02:30 UTC, KolomboPulse commented on aiosqlite/core.py
> +                self._connection = await future
self._connection = await future